<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPzjhc77\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPzjhc77/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPzjhc77.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPzjhc77\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPzjhc77\appProdProjectContainer([
    'container.build_hash' => 'Pzjhc77',
    'container.build_id' => '8bc64d7a',
    'container.build_time' => 1649687779,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPzjhc77');
